apiVersion: spectrum.cloudflare.m.crossplane.io/v1beta1
kind: Application
metadata:
  namespace: default
  name: example
spec:
  forProvider:
    zone: 1234
    protocol: tcp/80
    ipFirewall: false
    proxyProtocol: simple
    originPort:
      port: 80
    dns:
      type: ADDRESS
      name: domain.in.zone

  providerConfigRef:
    name: example
